spring:
  application:
    name: xiami-blog-springcloud-zuul
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    # 自定义名字
    api-a:
      path: /api/a/**
      serviceId: xiami-blog-springcloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: xiami-blog-springcloud-web-admin-feign

